#!/bin/bash -e
# shellcheck disable=SC1091
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Main script to manage resources

# Print usage information
usage() {
    echo "Usage: $0 [--create-vol volume_name | --create-net network_name | --create-cont num_containers image_name command volume_name network_name | --cleanup-vol volume_name | --cleanup-net network_name | --cleanup-cont num_containers | --list-procs | --list-vols | --list-nets]"
    exit 1
}

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
    usage
fi

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --create-vol)
            shift
            ./volume.sh create "$1" "$2"
            ;;
        --create-net)
            shift
            ./network.sh create "$1" "$2"
            ;;
        --create-cont)
            shift
            ./podman.sh create "$1" "$2" "$3" "$4" "$5" "$6"
            shift 5
            ;;
        --cleanup-vol)
            shift
            ./volume.sh remove "$1" "$2"
            ;;
        --cleanup-net)
            shift
            ./network.sh remove "$1" "$2"
            ;;
        --cleanup-cont)
            shift
            ./podman.sh remove "$1" "$2"
            ;;
        --list-procs)
            ./processes.sh list
            ;;
        --list-vols)
            ./volume.sh list
            ;;
        --list-nets)
            ./network.sh list
            ;;
    esac
    shift
done
