#!/bin/bash

source /usr/share/podman-stressor/constants
source /usr/share/podman-stressor/date
source /usr/share/podman-stressor/system

# network and volume definition to be used in remove and creation
NETNAME="my_network"
VOLNAME="my_volume"

# just to make sure our example will work
cleanenv() {
    echo -e "[ ${BLUE}INFO${NC} ] Cleaning any file from previous tests..."
    sudo podman volume rm "${VOLNAME}" --force &> /dev/null
    sudo podman network rm "${NETNAME}" --force &> /dev/null
}

# calling the function
cleanenv

echo -e "[ ${BLUE}INFO${NC} ] Executing test: service must be disabled in the distro: [podman]"
echo -e "[ ${BLUE}INFO${NC} ] This test was executed in the following criteria:"
echo -e "[ ${BLUE}INFO${NC} ]"
current_date
system_info
echo -e "[ ${BLUE}INFO${NC} ]"

# executing the program in previous dir
pushd ../../../ 1> /dev/null || exit 1

    sudo CLEANUP=false \
         VERBOSE=false \
         NETWORK_NAME="${NETNAME}" \
         VOLUME_NAME="${VOLNAME}" \
         IMAGE_COMMAND="sleep 3600" \
         IMAGE_NAME="quay.io/centos-sig-automotive/automotive-osbuild" \
         NUMBER_OF_CONTAINERS="1" \
         SERVICE_MUST_BE_DISABLED="podman" \
         ./podman-stressor

popd 1> /dev/null || exit 1
