#!/bin/bash

pushd .. 1> /dev/null
    ./podman-stressor \
       --network "my_network" \
       --volume "my_volume" \
       --number-of-containers 2 \
       --image-name "alpine" \
       --image-command "sleep 3600" # \
       # --cleanup # \
       #--list-current-state \
       #--verbose
popd 1> /dev/null

podman ps
podman network ls
podman volume ls
